insert into Team (_APIkey, _teamCity, _teamFullName, _teamConference, _teamDivision, _teamSeason) values ('ce2052d8bae043e4b4bc2dd49df78dfe', 'Varberg', 'Drongo, fork-tailed', 'NFC', 'WEST', 2019);
insert into Team (_APIkey, _teamCity, _teamFullName, _teamConference, _teamDivision, _teamSeason) values ('ce2052d8bae043e4b4bc2dd49df78dfe', 'Xiayang', 'Cormorant, large', 'NFC', 'EAST', 2019);
insert into Team (_APIkey, _teamCity, _teamFullName, _teamConference, _teamDivision, _teamSeason) values ('ce2052d8bae043e4b4bc2dd49df78dfe', 'Lokosovo', 'Weaver, chestnut', 'AFC', 'SOUTH', 2019);
insert into Team (_APIkey, _teamCity, _teamFullName, _teamConference, _teamDivision, _teamSeason) values ('ce2052d8bae043e4b4bc2dd49df78dfe', 'Waru', 'Sparrow, rufous-collared', 'AFC', 'SOUTH', 2019);
insert into Team (_APIkey, _teamCity, _teamFullName, _teamConference, _teamDivision, _teamSeason) values ('ce2052d8bae043e4b4bc2dd49df78dfe', 'Pangrumasan', 'Galapagos penguin', 'NFC', 'NORTH', 2019);
insert into Team (_APIkey, _teamCity, _teamFullName, _teamConference, _teamDivision, _teamSeason) values ('ce2052d8bae043e4b4bc2dd49df78dfe', 'Weton', 'Sulfur-crested cockatoo', 'NFC', 'WEST', 2019);
insert into Team (_APIkey, _teamCity, _teamFullName, _teamConference, _teamDivision, _teamSeason) values ('ce2052d8bae043e4b4bc2dd49df78dfe', 'Inhambupe', 'Baleen whale', 'AFC', 'NORTH', 2019);
insert into Team (_APIkey, _teamCity, _teamFullName, _teamConference, _teamDivision, _teamSeason) values ('ce2052d8bae043e4b4bc2dd49df78dfe', 'Naawan', 'Red-billed tropic bird', 'AFC', 'SOUTH', 2019);
insert into Team (_APIkey, _teamCity, _teamFullName, _teamConference, _teamDivision, _teamSeason) values ('ce2052d8bae043e4b4bc2dd49df78dfe', 'Dubki', 'Otter, small-clawed', 'NFC', 'NORTH', 2019);
insert into Team (_APIkey, _teamCity, _teamFullName, _teamConference, _teamDivision, _teamSeason) values ('ce2052d8bae043e4b4bc2dd49df78dfe', 'Huanghuatan', 'Langur, hanuman', 'NFC', 'EAST', 2019);
