package test.com.Project.Controller;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
public class IncorrectLoginTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "C:\\temp\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void incorrectLogin() {
    driver.get("http://localhost:8080/DisneyPrincessProjectIteration3/LoginPage.jsp");
    driver.manage().window().setSize(new Dimension(654, 767));
    driver.findElement(By.id("user")).click();
    driver.findElement(By.id("user")).sendKeys("bro");
    driver.findElement(By.id("pass")).sendKeys("ham");
    driver.findElement(By.id("sub")).click();
  }
}

